title: Gorkha Dev
email: gorkhadeveloper@gmail.com
year: 2024
tagline: Saving the World from Bad Softwares
description: >-
  We are group of brave, loyal, cultured, disciplined and
  professional Software Developers from Nepal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gorkha.dev" # the base hostname & protocol for your site, e.g. http://example.com
# asset_url: /assets                              # local assets: ending without forward slash
asset_url: https://gorkhadev.sirv.com        # cdn assets: ending without forward slash
thumbnail: thumbnail.jpg

author: Dhanu
author_url: https://dhanusir.com
channel_link: https://t.me/gorkhadev

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

google_analytics:
# Disqus Comments
disqus:
  shortname: gorkhadev

contacts:
  linkedin:
    url: https://www.linkedin.com/company/gorkhadev
    label: LinkdIn
    class: fab fa-linkedin-in
    img: linkedin.png
  facebook:
    url: https://www.facebook.com/gorkhadevnepal
    label: Facebook
    class: fab fa-facebook-f
    img: facebook.png
  twitter:
    url: https://twitter.com/gorkhadeveloper
    label: Twitter
    class: fab fa-twitter
    username: "@dhanumentor"
    img: twitter.png
  # instagram:
  #   url: https://instagram.com/c2edev
  #   label: YouTube Channel
  #   class: fa-brands fa-instagram
  #   img: youtube.png
  github:
    url: https://github.com/gorkhadev
    label: GitHub
    class: fab fa-github
    img: github.png
  # tiktok:
  #   url: https://tiktok.com/@c2edev
  #   label: YouTube Channel
  #   class: fa-brands fa-tiktok
  #   img: youtube.png
  email:
    url: mailto:gorkhadeveloper@gmail.com
    label: Email
    class: fas fa-envelope
    img: mail.png
  youtube:
    url: https://www.youtube.com/@gorkhadev
    label: YouTube Channel
    class: fab fa-youtube
    img: youtube.png

collections:
  missions:
    output: true
  workshops:
    output: true
  events:
    output: true

paginate: 6
paginate_path: "/blogs/page:num"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
exclude:
  - vagrant.cfg/*
  - Vagrant

