title: Dhanu Sir
email: dhanusirofficial@gmail.com
year: 2024
tagline: 12+ Years of IT Experience
description: >-
  Helping businesses or individual with Growth
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dhanusir.com" # the base hostname & protocol for your site, e.g. http://example.com
# asset_url: /assets                        # local assets: ending without forward slash
asset_url: https://dhanusir.sirv.com        # cdn assets: ending without forward slash
thumbnail: thumbnail.jpg

author: Dhanu
author_url: https://dhanusir.com
channel_link: https://t.me/dhanusirchannel

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

google_analytics: G-PSKFQHJ0VY
# Disqus Comments
disqus:
  shortname: dhanusir

contacts:
  linkedin:
    url: https://www.linkedin.com/in/dhanusir
    label: LinkdIn
    class: fab fa-linkedin-in
    img: linkedin.png
  facebook:
    url: https://www.facebook.com/dhanusir
    label: Facebook
    class: fab fa-facebook-f
    img: facebook.png
  twitter:
    url: https://twitter.com/gorkhadeveloper
    label: Twitter
    class: fab fa-twitter
    username: "@dhanumentor"
    img: twitter.png
  instagram:
    url: https://instagram.com/dhanusirofficial
    label: YouTube Channel
    class: fa-brands fa-instagram
    img: youtube.png
  github:
    url: https://github.com/dhanusir
    label: GitHub
    class: fab fa-github
    img: github.png
  # tiktok:
  #   url: https://tiktok.com/@dhanusirofficial
  #   label: YouTube Channel
  #   class: fa-brands fa-tiktok
  #   img: youtube.png
  email:
    url: mailto:dhanusirofficial@gmail.com
    label: Email
    class: fas fa-envelope
    img: mail.png
  youtube:
    url: https://www.youtube.com/@dhanusir
    label: YouTube Channel
    class: fab fa-youtube
    img: youtube.png
  # discord:
  #   url: https://discord.gg/hwNSzvE92F
  #   label: Discord
  #   class: fab fa-discord
  #   img: discord.png

collections:
  tutorials:
    output: true
  getting_tastes:
    output: true
  exercises:
    output: true
  projects:
    output: true
  bootcamps:
    output: true
  workshops:
    output: true

paginate: 6
paginate_path: "/blogs/page:num"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
exclude:
  - vagrant.cfg/*
  - Vagrant

