title: TECH Setu
email: techsetuu@gmail.com
year: 2022
description: >-
  A non-profit organization bridging the gap between People and Tech Industry
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techsetu.org" # the base hostname & protocol for your site, e.g. http://example.com
asset_base_url: /assets                                     # local assets: ending without forward slash
# asset_base_url: https://technologychannel.sirv.com        # cdn assets: ending without forward slash
thumbnail: thumbnail.jpg

author: BRG
author_url: https://dhanugurung.com

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

google_analytics: G-RXN8QR661J
# Disqus Comments
disqus:
  shortname: brg-trainings

contacts:
  facebook:
    url: https://www.facebook.com/techsetu.org
    label: Facebook
    class: fab fa-facebook-f
    img: facebook.png
  # twitter:
  #   url: https://twitter.com/techchannelnp
  #   label: Twitter
  #   class: fab fa-twitter
  #   username: "@coolbrg"
  #   img: twitter.png
  github:
    url: https://github.com/techsetu
    label: GitHub
    class: fab fa-github
    img: github.png
  linkedin:
    url: https://www.linkedin.com/company/techsetu
    label: LinkdIn
    class: fab fa-linkedin-in
    img: linkedin.png
  email:
    url: mailto:info@techsetu.com
    label: Email
    class: fas fa-envelope
    img: mail.png
  youtube:
    url: https://www.youtube.com/channel/UC8p8tlnY5fykNYv2vZHvQDg
    label: YouTube Channel
    class: fab fa-youtube
    img: youtube.png
  # discord:
  #   url: https://discord.gg/hwNSzvE92F
  #   label: Discord
  #   class: fab fa-discord
  #   img: discord.png

collections:
  tutorials:
    output: true
  getting_tastes:
    output: true
  exercises:
    output: true
  projects:
    output: true
  bootcamps:
    output: true

paginate: 6
paginate_path: "/blogs/page:num"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
