title: Dhanu Sir
email: contact@dhanusir.com
year: 2023
tagline: 11+ Years of IT Experience
description: >-
  Helping IT Students and Professionals in their Career Growth
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dhanusir.com" # the base hostname & protocol for your site, e.g. http://example.com
asset_base_url: /assets                                     # local assets: ending without forward slash
# asset_base_url: https://dhanugurung.sirv.com        # cdn assets: ending without forward slash
thumbnail: thumbnail.jpg

author: Dhanu
author_url: https://dhanusir.com

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

google_analytics: G-MRQN1VZ14Y
# Disqus Comments
disqus:
  shortname: dhanusir

contacts:
  facebook:
    url: https://www.facebook.com/dhanusir
    label: Facebook
    class: fab fa-facebook-f
    img: facebook.png
  twitter:
    url: https://twitter.com/dhanumentor
    label: Twitter
    class: fab fa-twitter
    username: "@dhanumentor"
    img: twitter.png
  github:
    url: https://github.com/dhanugurung
    label: GitHub
    class: fab fa-github
    img: github.png
  linkedin:
    url: https://www.linkedin.com/in/dhanumentor
    label: LinkdIn
    class: fab fa-linkedin-in
    img: linkedin.png
  email:
    url: mailto:contact@dhanusir.com
    label: Email
    class: fas fa-envelope
    img: mail.png
  youtube:
    url: https://www.youtube.com/@dhanumentor
    label: YouTube Channel
    class: fab fa-youtube
    img: youtube.png
  # discord:
  #   url: https://discord.gg/hwNSzvE92F
  #   label: Discord
  #   class: fab fa-discord
  #   img: discord.png

collections:
  tutorials:
    output: true
  getting_tastes:
    output: true
  exercises:
    output: true
  projects:
    output: true
  bootcamps:
    output: true

paginate: 6
paginate_path: "/blogs/page:num"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
